config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'significances' => 'significances#index'
  
  get 'about' => 'static_pages#about'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'

  get 'flowers/:id/edit_discussion', to: 'flowers#edit_discussion', as: 'edit_discussion'
  get 'flowers/:id/edit_experiences', to: 'flowers#edit_experiences', as: 'edit_experiences'

  get 'colour/:colour', to: 'application#colour'

  root 'static_pages#home'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :flowers, :concerns => :paginatable
  resources :users

end

app/models/flower.rb
class Flower
  include Mongoid::Document
  include Mongoid::Slug
  # include Mongoid::Paperclip
  include Mongoid::Elasticsearch
  elasticsearch!
  embeds_many :variants
  accepts_nested_attributes_for :variants
  field :name, type: String
  slug :name
  field :other_names, type: String
  field :bot_name, type: String
  field :family, type: String
  field :significance, type: String
  field :comment, type: String
  field :description, type: String
  field :type, type: String
  field :colour, type: String
  field :petals, type: String
  field :rows, type: String
  field :size, type: String
	field :place, type: String
	field :climate, type: String
  field :quotes, type: Array
  field :discussion, type: String
  field :experiences, type: String
  field :image_url, type: String
  field :thumbnail_url, type: String
  field :source, type: String
  field :url, type: String

  # has_mongoid_attached_file :image
  # validates_attachment_presence :image
  # validates_attachment_content_type :image,
  #                                   :content_type => ['image/jpeg', 'image/png', 'image/jpg']




  # dimensions, photographs, stories

  # validates_presence_of :name, :significance,
  #                       :petals, :colour, :description,
  #                       :place, :climate, :season, :size
                        
  # validates_presence_of :image_url, :message => "Please upload an image"

  # validates_presence_of :bot_name, :message => "Botanical name must be present"

  # validates_format_of :image_url, :with => %r{\.(png|jpg|gif)}i,
  #                                 :message => "The image must be a png or jpg"

  # validates_uniqueness_of :name, :bot_name, :image_url

end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
	before_action :logged_in_user, :not_authorized?, only: [:edit, :update, :destroy]
	def index
		if params[:query].present?
			@query = params[:query]
			results_per_page = 9
			query = {
				body: {
					query: {
						query_string: {
							query: @query
						}
					},
					size: results_per_page
				}
			}
			from_page = (params[:page].to_i - 1) * results_per_page unless params[:page].nil?
			query[:body][:from] = from_page unless from_page.nil?
		  # result = Flower.es.search(@query)
			# response = result.raw_response
			@flowers = Flower.es.search(query, page: params[:page])
			# AA
			@size = @flowers.count
		else
			@flowers = Flower.asc(:name).page params[:page]
		end
		respond_to do |format|
			format.html
			format.json { render json: @flowers }
		end
	end

	def show
		@flower = Flower.find(params[:id])
		@previous = Flower.where(:_slugs.lt => @flower._slugs[0]).desc(:_slugs).first
		@next = Flower.where(:_slugs.gt => @flower._slugs[0]).asc(:_slugs).first
		if @previous.present?
			previous_flower = {
				name: @previous.name,
				url: request.protocol + request.host_with_port + "/flowers/" + @previous._slugs.first
			}
		end

		if @next.present?
			next_flower = {
				name: @next.name,
				url: request.protocol + request.host_with_port + "/flowers/" + @next._slugs.first
			}
		end

		respond_to do |format|
			format.html
			format.json do
				if @flower.quotes.present?
					flower_quotes = @flower.quotes.map { |quote| Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(quote).html_safe }
				end
				if @flower.variants.present?
					@flower.variants.each do |variant|
						if variant.quotes.present?
							variant.quotes = variant.quotes.map { |quote| Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(quote).html_safe }
						end
					end
				end
        render :json => @flower.attributes.merge({:previous => previous_flower, :next => next_flower, :quotes => flower_quotes})
      end
		end
	end

	def new
		@flower = Flower.new
	end

	def create
		@flower = Flower.new(flower_params)
		if @flower.save
			flash[:success] = "Flower added"
			redirect_to @flower
		else
			render 'new'
		end
	end

	def edit
		@flower = Flower.find(params[:id])
	end

	def edit_discussion
		@flower = Flower.find(params[:id])
	end

	def edit_experiences
		@flower = Flower.find(params[:id])
	end

	def update
		@flower = Flower.find(params[:id])
		if @flower.update_attributes(flower_params)
			#HEHE
			flash[:success] = "Flower updated"
			redirect_to @flower
		else
			render 'edit'
		end
	end

	def destroy
		Flower.find(params[:id]).destroy
		flash[:success] = "Flower deleted"
		redirect_to flowers_url
	end

	private

		def flower_params
			params.require(:flower).permit(:name, :bot_name, :significance,
																		 :petals, :colour, :description,
																		 :place, :climate, :season, :size,
																		 :discussion, :experiences, :image_url,
																		 :variants_attributes)
			#HEHE
		end

		def logged_in_user
			if !logged_in?
				flash[:danger] = "Please sign in"
				redirect_to signin_path
			end
		end

		def not_authorized?
			if !is_admin?
				flash[:danger] = "You can't do that"
				redirect_to flowers_url
			end
		end
end

app/helpers/flowers_helper.rb
module FlowersHelper
#   def get_flower_rows
#     flower_rows = []
#     flower_rows << @flowers[0..2]
#     flower_rows << @flowers[3..5]
#     flower_rows << @flowers[6..8]
#     flower_rows
#   end
end

app/views/flowers/_description.html.erb
<div class="details">

  <% if is_admin? %>
    <%= link_to "edit", edit_flower_path(@flower), class: "option", style: "float: right;" %>
  <% end %>

  <h1 class="flower_heading"><%= @flower.name %></h1>

  <% if @flower.bot_name.present? %>
    <h3 class="botanical_name">(<%= @flower.bot_name %>)</h3>
  <% end %>
      
  <% if @flower.image_url %>
    <% flower_url = ENV['AMAZON_IMAGE_PATH'] + @flower.image_url %>
    <script type="text/javascript">
      window.image_url = "<%= flower_url %>";
    </script>
    <%= link_to image_tag('', :class => "img-responsive main-img"), flower_url,:rel => "lightbox", :data => {lightbox: @flower.name.to_url, title: @flower.name}%>
    <a href="<%= @flower.url %>" target="_blank" class="img-source" style="padding-bottom: 30px;"><%= @flower.source %></a>
  <% end %>

  <% if @flower.significance.present? %>
    <p class="flower_subheading" style="clear: both;">Significance given by the Mother</p>
    <p class="lead significance"><%= @flower.significance %></p>
  <% end %>

  <% if @flower.comment.present? %>
    <p class="flower_subheading">The Mother&rsquo;s Comment</p>
    <p class="lead comment"><%= @flower.comment %></p>
  <% end %>

  <% if @flower.description.present? %>
    <p class="flower_subheading">Description</p>
    <p class="t5"><%= @flower.description %></p>
  <% end %>

  <!-- Variants present -->
  <% if @flower.variants.count > 0 %>
    <div class="row">
      <div class="col-md-4 col-md-offset-5 col-sm-5 col-sm-offset-5 col-xs-5 col-xs-offset-4" style="margin-top: 1em; margin-bottom: 0.5em">
        <p class="t3">Variants</p>
      </div>
    </div>

    <% @flower.variants.each_with_index do |variant, i| %>
      <% if i > 0 %>
        <hr>
      <% end %>
      <% if is_admin? %>
        <%= link_to "edit", '#', class: "option", style: "float: right;" %>
        <br/>
      <% end %>

      <div class="row variant">
        <% variant_url = ENV['AMAZON_IMAGE_PATH'] + variant.image_url %>
        <% variant_anchor = variant.significance ? variant.significance.to_url : variant.colour.to_url %>
        <a class="variant-anchor" href="#<%= variant_anchor %>" id="<%= variant_anchor %>"></a>

        <% if variant.bot_name.present? %>
          <p class="botanical_name">(<%= variant.bot_name %>)</p>
        <% end %>
        
        <div class="<%= i % 2 == 0 ? 'col-md-8' : 'col-md-8 col-md-push-4' %>">
          <div class="row">
            <div class="col-xs-12">
              <%= link_to image_tag(variant_url, :class => "img-responsive variant-img"), variant_url,:rel => "lightbox", :data => {lightbox: @flower.name.to_url, title: @flower.name + " &mdash; " + variant.colour}%>
              <a href="<%= variant.url %>" target="_blank" class="img-source"><%= variant.source %></a>
            </div>
          </div>
          <% if variant.significance.present? %>
            <div class="row" style="margin-top: 20px">
              <div class="col-xs-12">
                <p class="variant-subheading">Significance given by the Mother</p>
                <p class="lead"><%= variant.significance %></p>
              </div>
            </div>
          <% end %>
          <% if variant.comment.present? %>
            <div class="row">
              <div class="col-xs-12">
                <p class="variant-subheading">The Mother&rsquo;s Comment</p>
                <p class="lead"><%= variant.comment %></p>
              </div>
            </div>
          <% end %>
        </div>
        <div class="<%= i % 2 == 0 ? 'col-md-4' : 'col-md-4 col-md-pull-8' %>">
          <p class="flower_subheading">Description</p>
          <p class="t5"><%= variant.description %></p>
          <p class="flower_subheading">Colour</p>
          <p class="t5"><%= variant.colour %></p>
        </div>
      </div>
    <% end %>
      
  <% end %>
  <div class="col-md-3 col-xs-12 sidebar">
    <% if @flower.family.present? %>
      <div class="side-details">
        <p class="flower_subheading">Family</p>
        <p class="t5"><%= @flower.family %></p>
      </div>
    <% end %>

    <% if @flower.other_names.present? %>
      <div class="side-details">
        <p class="flower_subheading">Other Names</p>
        <p class="t5"><%= @flower.other_names %></p>
      </div>
    <% end %>

    <% if @flower.colour.present? %>
      <div class="side-details">
        <p class="flower_subheading">Colour</p>
        <p class="t5"><%= @flower.colour %></p>
      </div>
    <% end %>

    <% if @flower.petals.present? %>
      <div class="side-details">
        <p class="flower_subheading">Petals</p>
        <p class="t5"><%= @flower.petals %></p>
      </div>
    <% end %>

    <% if @flower.size.present? %>
      <div class="side-details">
        <p class="flower_subheading">Size</p>
        <p class="t5"><%= @flower.size %></p>
      </div>
    <% end %>

    <div class="side-details">
      <p class="flower_subheading">Cultivation</p>
      <p class="t5"><%= @flower.place %></p>
    </div>

    <div class="side-details">
      <p class="flower_subheading">Climate</p>
      <p class="t5"><%= @flower.climate %></p>
    </div>
  </div>
</div>

app/views/flowers/_details.html.erb
<div class="row">
  <div class="col-md-9 col-xs-12">
    <div class="details">
      <% if is_admin? %>
        <%= link_to "edit", edit_flower_path(@flower), class: "option", style: "float: right;" %>
      <% end %>
      <h1 class="flower_heading"><%= @flower.name %></h1>

      <% if @flower.bot_name.present? %>
        <h3 class="botanical_name">(<%= @flower.bot_name %>)</h3>
      <% end %>
      
      <% if @flower.image_url %>
        <% flower_url = ENV['AMAZON_IMAGE_PATH'] + @flower.image_url %>
        <script type="text/javascript">
          window.image_url = "<%= flower_url %>";
        </script>
        <%= link_to image_tag('', :class => "img-responsive main-img"), flower_url,:rel => "lightbox", :data => {lightbox: @flower.name.to_url, title: @flower.name}%>
        <a href="<%= @flower.url %>" target="_blank" class="img-source" style="padding-bottom: 30px;"><%= @flower.source %></a>
      <% end %>

      <% if @flower.significance.present? %>
        <p class="flower_subheading" style="clear: both;">Significance given by the Mother</p>
        <p class="lead significance"><%= @flower.significance %></p>
      <% end %>

      <% if @flower.comment.present? %>
        <p class="flower_subheading">The Mother&rsquo;s Comment</p>
        <p class="lead comment"><%= @flower.comment %></p>
      <% end %>

      <% if @flower.description.present? %>
        <p class="flower_subheading">Description</p>
        <p class="t5"><%= @flower.description %></p>
      <% end %>

      <% if @flower.quotes.present? %>
        <p class="flower_subheading">Quotes</p>
        <div class="md-quote">
          <% @flower.quotes.each_with_index do |quote, i| %>
            <% if i > 0 %>
              <%= markdown("---").html_safe %>
            <% end %>
            <%= markdown(quote).html_safe %>
          <% end %>
        </div>
      <% end %>

      <% if @flower.variants.count > 0 %>
        <div class="row">
          <div class="col-md-4 col-md-offset-5 col-sm-5 col-sm-offset-5 col-xs-5 col-xs-offset-4" style="margin-top: 1em; margin-bottom: 0.5em">
            <p class="t3">Variants</p>
          </div>
        </div>

        <% @flower.variants.each_with_index do |variant, i| %>
          <% if i > 0 %>
            <hr>
          <% end %>
          <% if is_admin? %>
            <%= link_to "edit", '#', class: "option", style: "float: right;" %>
            <br/>
          <% end %>

          <div class="row variant">
          <% variant_url = ENV['AMAZON_IMAGE_PATH'] + variant.image_url %>
          <% variant_anchor = variant.significance ? variant.significance.to_url : variant.colour.to_url %>
          <a class="variant-anchor" href="#<%= variant_anchor %>" id="<%= variant_anchor %>"></a>
            <% if variant.bot_name.present? %>
              <p class="botanical_name">(<%= variant.bot_name %>)</p>
            <% end %>
            <div class="<%= i % 2 == 0 ? 'col-md-8' : 'col-md-8 col-md-push-4' %>">
              <div class="row">
                <div class="col-xs-12">
                  <%= link_to image_tag(variant_url, :class => "img-responsive variant-img"), variant_url,:rel => "lightbox", :data => {lightbox: @flower.name.to_url, title: @flower.name + " &mdash; " + variant.colour}%>
                  <a href="<%= variant.url %>" target="_blank" class="img-source"><%= variant.source %></a>
                </div>
              </div>
              <% if variant.significance.present? %>
                <div class="row" style="margin-top: 20px">
                  <div class="col-xs-12">
                    <p class="variant-subheading">Significance given by the Mother</p>
                    <p class="lead"><%= variant.significance %></p>
                  </div>
                </div>
              <% end %>
              <% if variant.comment.present? %>
                <div class="row">
                  <div class="col-xs-12">
                      <p class="variant-subheading">The Mother&rsquo;s Comment</p>
                      <p class="lead"><%= variant.comment %></p>
                  </div>
                </div>
              <% end %>
              <% if variant.quotes.present? %>
                <div class="row">
                  <div class="col-xs-12">
                    <p class="variant-subheading">Quotes</p>
                    <div class="md-quote">
                      <% variant.quotes.each do |quote| %>
                        <%= markdown(quote).html_safe %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="<%= i % 2 == 0 ? 'col-md-4' : 'col-md-4 col-md-pull-8' %>">
              <p class="flower_subheading">Description</p>
              <p class="t5"><%= variant.description %></p>
              <p class="flower_subheading">Colour</p>
              <p class="t5"><%= variant.colour %></p>
            </div>
          </div>
        <% end %>
      
      <% end %>
    </div>
  </div>
  <div class="col-md-3 col-xs-12 sidebar">
    <% if @flower.family.present? %>
      <div class="side-details">
        <p class="flower_subheading">Family</p>
        <p class="t5"><%= @flower.family %></p>
      </div>
    <% end %>

    <div class="side-details">
      <p class="flower_subheading">Type</p>
      <p class="t5"><%= @flower.type %></p>
    </div>

    <% if @flower.other_names.present? %>
      <div class="side-details">
        <p class="flower_subheading">Other Names</p>
        <p class="t5"><%= @flower.other_names %></p>
      </div>
    <% end %>

    <% if @flower.colour.present? %>
      <div class="side-details">
        <p class="flower_subheading">Colour</p>
        <p class="t5"><%= @flower.colour %></p>
      </div>
    <% end %>

    <% if @flower.petals.present? %>
      <div class="side-details">
        <p class="flower_subheading">Petals</p>
        <p class="t5"><%= @flower.petals %></p>
      </div>
    <% end %>

    <% if @flower.size.present? %>
      <div class="side-details">
        <p class="flower_subheading">Size</p>
        <p class="t5"><%= @flower.size %></p>
      </div>
    <% end %>

    <div class="side-details">
      <p class="flower_subheading">Distribution</p>
      <p class="t5"><%= @flower.place %></p>
    </div>

    <div class="side-details">
      <p class="flower_subheading">Climate</p>
      <p class="t5"><%= @flower.climate %></p>
    </div>

    <div class="scroll">
      <a href="#" class="flower_nav">
        <span class="glyphicon glyphicon-menu-up flower_nav_button"></span>
      </a>
    </div>
  </div>
    
</div>

app/views/flowers/_discussion.html.erb
<div class="row">
  <div class="col-md-12 col-xs-12">
    <div class="details">
      <% if @flower.discussion.present? %>
        <% if is_admin? %>
          <%= link_to "edit", edit_discussion_path(@flower), class: "option", style: "float: right;" %>
        <% end %>
        <div class="md-discussion">
          <%= markdown(@flower.discussion).html_safe %>
        </div>
      <% else %>
        <h1>Discuss <%= @flower.name %></h1>
        <%= form_for @flower do |f| %>
          <%= f.text_area :discussion, rows: 10, class: "form-control" %>
          <div class="row">
            <div class="col-md-6", style="margin-top: 1em;">
              <%= f.submit "Update", class: "btn btn-md btn-primary" %>
            </div>
            <div class="col-md-6", style="margin-top: 1em;">
              <%= link_to "Cancel", flower_path(@flower), class: "btn btn-md btn-danger", style: "width: 100%;" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/flowers/_experiences.html.erb
<div class="row">
  <div class="col-md-12 col-xs-12">
    <div class="details">
      <% if @flower.experiences.present? %>
      	<h1>Experiences with <%= @flower.name %></h1>
        <% if is_admin? %>
          <%= link_to "edit", edit_experiences_path(@flower), class: "option", style: "float: right;" %>
        <% end %>
        <div class="md-discussion">
          <%= markdown(@flower.experiences).html_safe %>
        </div>
      <% else %>
        <h1>Share your experiences about <%= @flower.name %></h1>
        <%= form_for @flower do |f| %>
          <%= f.text_area :experiences, rows: 10, class: "form-control" %>
          <div class="row">
            <div class="col-md-6", style="margin-top: 1em;">
              <%= f.submit "Update", class: "btn btn-md btn-primary" %>
            </div>
            <div class="col-md-6", style="margin-top: 1em;">
              <%= link_to "Cancel", flower_path(@flower), class: "btn btn-md btn-danger", style: "width: 100%;" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/flowers/_list.html.erb
<!-- http://colintoh.com/blog/display-table-anti-hero -->
<!-- https://css-tricks.com/almanac/properties/d/display/ -->
<!-- https://developer.mozilla.org/en-US/docs/Web/CSS/display -->

<div class="media", style="clear: both;">
  <% @flowers.each do |flower| %>
    <div class="col-md-4 col-sm-12">
      <%= link_to flower do %>
        <div class="name_card" align="center">
          <%= image_tag(ENV['AMAZON_IMAGE_PATH'] + flower.thumbnail_url, class: "media-object img-circle", height: '165', width: '165') %>
          <br/>
          <p class="flower_name"><%= flower.name %></p>
          <% if is_admin? %>
            <span class="option">
              <%= link_to "edit", edit_flower_path(flower) %>
              | <%= link_to "delete", flower, method: :delete,
                                              data: { confirm: "Delete this flower?" } %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @flowers %>

app/views/flowers/edit.html.erb
<% provide(:title, "Edit") %>
<h1 class="nice_heading">Edit this flower</h1>
<hr>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@flower) do |f| %>
			<%= render 'flower_fields', f: f %>

			<% flower_url = ENV['AMAZON_IMAGE_PATH'] + @flower.image_url %>
			
			<%= image_tag(flower_url, class: "photo img-responsive", style: "margin: 2em 0;") %>

			<%= f.label :image_url, "New image URL", class: "form_field" %>
			<!-- Use file_field to choose file -->
			<%= f.text_field :image_url, class: "form-control" %>

			<% if @flower.variants.present? %>
				<hr>
				<h1 class="nice_heading">Variants</h1>
					<%= f.fields_for :variants do |builder|%>
					
						<%= builder.label :bot_name, "Botanical name", class: "form_field" %>
						<%= builder.text_field :bot_name, class: "form-control" %>

						<%= builder.label :significance, class: "form_field"%>
						<%= builder.text_area :significance, rows: 6, class: "form-control" %>

						<%= builder.label :colour, class: "form_field" %>
						<%= builder.text_field :colour, class: "form-control" %>

						<%= builder.label :description, class: "form_field" %>
						<%= builder.text_area :description, rows: 6, class: "form-control" %>

						<%= builder.label :image_url, "New image URL", class: "form_field" %>
						<!-- Use file_field to choose file -->
						<%= builder.text_field :image_url, class: "form-control" %>
						<hr/>
					<% end %>
			<% end %>

			<div class="row">
				<div class="col-md-6", style="margin-top: 1em;">
					<%= f.submit "Update", class: "btn btn-lg btn-primary" %>
				</div>
			  <div class="col-md-6", style="margin-top: 1em;">
					<%= link_to "Cancel", flower_path(@flower), class: "btn btn-lg btn-danger", style: "width: 100%;" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/flowers/edit_discussion.html.erb
<% provide(:title, "Discuss") %>
<h1 class="nice_heading">Edit Discussion for <%= @flower.name %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@flower) do |f| %>
      <%= f.text_area :discussion, rows: 6, class: "form-control" %>
      <div class="row">
        <div class="col-md-6", style="margin-top: 1em;">
          <%= f.submit "Update", class: "btn btn-lg btn-primary" %>
        </div>
        <div class="col-md-6", style="margin-top: 1em;">
          <%= link_to "Cancel", flower_path(@flower), class: "btn btn-lg btn-danger", style: "width: 100%;" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flowers/edit_experiences.html.erb
<% provide(:title, "Share Your Experiences") %>
<h1 class="nice_heading">Edit Experiences for <%= @flower.name %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@flower) do |f| %>
      <%= f.text_area :experiences, rows: 6, class: "form-control" %>
      <div class="row">
        <div class="col-md-6", style="margin-top: 1em;">
          <%= f.submit "Update", class: "btn btn-lg btn-primary" %>
        </div>
        <div class="col-md-6", style="margin-top: 1em;">
          <%= link_to "Cancel", flower_path(@flower), class: "btn btn-lg btn-danger", style: "width: 100%;" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flowers/index.html.erb
<!-- Heading amd list -->
<% if @query.present? %>
	<% provide(:title, "Search Results") %>

	<% if @size.to_i > 0 %>
		<h1 class="nice_heading">
			Found <%= pluralize(@size, "result") %>
		</h1>
		<%= render 'list' %>
	<% else %>
		<p class="lead", style="clear: both; text-align: center;">
			Sorry, we're fresh out of <%= @query %>!
		</p>
	<% end %>

<% else %>

	<% provide(:title, "Browse") %>

	<h1 class="page-header" style="margin-top: 0">Flowers</h1>
	
	<%= render 'list' %>

<% end %>

<!-- <h4 class="add"><%= link_to "+ Add your own", new_flower_path %></h4> -->

app/views/flowers/show.html.erb
<% provide(:title, @flower.name.html_safe) %>
<!-- <div class="row">
  <div class="text-center">
    <h1><%= @flower.name %></h1>
    <h3><em>(<%= @flower.bot_name %>)</em></h3>
  </div>
</div>
<div class="row center">
  <div class="col-md-10 col-md-offset-1">
      <%= image_tag(@flower.image_url, class: "img-responsive main-img") %>
  </div>
</div> -->
<!-- <div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button"></div> -->

<div class="hidden-xs hidden-sm">
  <% if !@previous.nil? %>
    <%= link_to flower_path(@previous), class: "flower_nav" do %>
      <span class="glyphicon glyphicon-menu-left flower_nav_button left-nav-button" id="left"></span>
      <span class="flower_nav_button nav_text" id="left-text"><%= @previous.name %></span>
    <% end %>
  <% end %>

  <% if !@next.nil? %>
    <%= link_to flower_path(@next), class: "flower_nav" do %>
      <span class="flower_nav_button nav_text" id="right-text"><%= @next.name %></span>
      <span class="glyphicon glyphicon-menu-right flower_nav_button right-nav-button" id="right"></span>
    <% end %>
  <% end %>
</div>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#flowerdetails" aria-controls="#flowerdetails" role="tab" data-toggle="tab">Details</a></li>
    <li role="presentation"><a href="#discussion" aria-controls="discussion" role="tab" data-toggle="tab">Discussion</a></li>
    <li role="presentation"><a href="#experiences" aria-controls="experiences" role="tab" data-toggle="tab">Experiences</a></li>    
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="flowerdetails">
      <%= render 'details' %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="discussion">
      <%= render 'discussion' %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="experiences">
      <%= render 'experiences' %>
    </div>
  </div>

</div>

<div class="flower_nav_text visible-xs-block visible-sm-block">

  <div class="row">
    <div class="col-xs-12">
      <div class="pull-left">
        <% if !@previous.nil? %>
          <%= link_to flower_path(@previous), class: "flower_nav" do %>
            <span class="glyphicon glyphicon-menu-left flower_nav_button left-nav-button"></span>
          <% end %>
        <% end %>
      </div>
      <div class="pull-right">
        <% if !@next.nil? %>
          <%= link_to flower_path(@next), class: "flower_nav" do %>
            <span class="glyphicon glyphicon-menu-right flower_nav_button right-nav-button"></span>
          <% end %>
        <% end %>  
      </div>
    </div>
  </div>

</div>