config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'significances' => 'significances#index'
  
  get 'about' => 'static_pages#about'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'

  get 'flowers/:id/edit_discussion', to: 'flowers#edit_discussion', as: 'edit_discussion'
  get 'flowers/:id/edit_experiences', to: 'flowers#edit_experiences', as: 'edit_experiences'

  get 'colour/:colour', to: 'application#colour'

  root 'static_pages#home'

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :flowers, :concerns => :paginatable
  resources :users

end

app/views/layouts/_footer.html.erb
<footer class="center footer">
  <span style="letter-spacing: 1px;font-weight: lighter">
      "Life must blossom like a flower offering itself to the Divine." &mdash; The Mother
  </span>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-67304665-1', 'auto');

</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default navbar-custom">
	<div class="container-fluid">
		<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      	<span class="sr-only">Toggle navigation</span>
      	<span class="icon-bar"></span>
      	<span class="icon-bar"></span>
        <span class="icon-bar"></span>
    	</button>
			<%= link_to "Flower Song", root_path, class: "navbar-brand" %>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
    	<ul class="nav navbar-nav navbar-right">
    		<li class="<%= 'active' if current_page?(flowers_path) %>"><%= link_to "Browse", flowers_path %></li>
        <li class="<%= 'active' if current_page?(significances_path) %>"><%= link_to "Significances", significances_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        <!-- <li class="<%= 'active' if current_page?(new_flower_path) %>"><%= link_to "New", new_flower_path %></li> -->
        <li>
          <!-- Search bar -->
          <%= form_tag flowers_path, method: "get", class: "navbar-form" do %>
            <div class="input-group input-group-sm" style="padding-top:4px;">
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search" %>
              <div class="input-group-btn">
                <button type="submit" class="btn btn-primary">Go</button>
              </div>
            </div>
          <% end %>
        </li>
        <% if current_user %>
          <li class="dropdown <%= 'active' if current_page?(user_path(current_user)) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= image_tag(current_user.image) %> <span class="hidden-md hidden-sm"><%= current_user.name %></span> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Your profile", user_path(current_user) %></li>
              <li role="presentation" class="divider"></li>
              <li><%= link_to "Sign out", signout_path %></li>
            </ul>
          </li>
        <% else %>
          <!-- <li class="<%= 'active' if current_page?(signin_path) %>"><%= link_to "Sign in", signin_path %></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign in <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "<i class='fa fa-facebook-official fa-fw'></i> Facebook".html_safe, user_omniauth_authorize_path(:facebook) %></li>
              <li><%= link_to "<i class='fa fa-google fa-fw'></i> Google".html_safe, user_omniauth_authorize_path(:google_oauth2) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->